apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: guess-game-notin
spec:
  params:
    - name: number
      description: Pick a number
      type: string
  tasks:
    - name: win
      params:
        - name: text
          value: You win
      taskRef:
        name: logger
      when: 
        - input: $(params.number)
          operator: in
          values: ["3"]
    - name: lose
      params:
        - name: text
          value: You lose
      taskRef:
        name: logger
      when:
        - input: $(params.number)
          operator: notin
          values: ["3"]