apiVersion: v1
kind: ServiceAccount
metadata:
  name: authenticated
secrets:
  - name: registry-creds
imagePullSecrets:
  - name: registry-creds
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: private
spec:
  steps:
    - image: joellord/private
      command: 
        - /bin/sh
        - -c
        - echo hello
