apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-auth-
spec:
  serviceAccountName: git-auth-sa
  params:
    - name: private-repo
      value: https://github.com/joellord/secret-repo.git
  taskRef:
    name: read-file