apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: logger
spec:
  params:
    - name: text
      type: string
  steps:
    - name: log
      image: registry.access.redhat.com/ubi8/ubi-minimal
      script: |
        DATE=$(date +%d/%m/%Y\ %T)
        echo [$DATE] - $(params.text)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-admin
spec:
  params:
    - name: username
      type: string
  tasks:
    - name: hello-admin
      taskRef:
        name: logger
      params:
        - name: text
          value: "Hello Admin"
      when:
        - input: $(params.username)
          operator: in
          values: ["admin"]
    - name: hello-other
      taskRef:
        name: logger
      params:
        - name: text
          value: "Hello User"
      when:
        - input: $(params.username)
          operator: notin
          values: ["admin"]