apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: write-read-workspace
spec:
  workspaces:
    - name: data
  params:
    - name: message
      default: "Hello World"
      type: string
      description: "Message to write in the workspace"
  steps:
    - name: write
      image: registry.access.redhat.com/ubi8/ubi
      command:
        - /bin/bash
      args: 
        - -c
        - echo "$(params.message)" > $(workspaces.data.path)/message.txt
    - name: read
      image: registry.access.redhat.com/ubi8/ubi
      command: 
        - /bin/bash
      args:
        - -c
        - cat $(workspaces.data.path)/message.txt